apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo-cm
  namespace: game-demo-ns
data:
  # property-like keys; each key maps to a simple value
  APP: "Demo Game"
  LOG_LEVEL: "DEBUG" 
  ENV: "PRODUCTION"
  index.html: |  # When mounted as a volume, this key creates a file named 'index.html' with the following contents.
    <!DOCTYPE html>
    <html>
    <head><title>Welcome</title></head>
    <body>
      <h1>This page is served by nginx. Welcome to Cloud With VarJosh!!</h1>
    </body>
    </html>