apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-demo-deployment
  namespace: game-demo-ns

spec:
  replicas: 1

  selector:
    matchLabels:
      app: secret-demo
  template:
    metadata:
      labels:
        app: secret-demo

    spec:
      containers:
      - name: demo
        image: alpine
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-game-secret
              key: DB_USER

        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-game-secret
              key: DB_PASSWORD

        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secrets"
      volumes:
      - name: secret-volume
        secret:
          secretName: demo-game-secret
          items:
          - key: DB_USER  
            path: DB_USER
          - key: DB_PASSWORD
            path: DB_PASSWORD